### PR TITLE
Fhmobsdk 19.use.cocoapods

### PR DESCRIPTION
**Pull request by corinnekrych**
This PR lined to FHMOBSDK-23 subtask:
- use cocoapods for dependencies
- add REAME instructions
- min deployment set to 7.0

@wei-lee is it ok?

PS: i've noticed this project is using [%id% templating](https://github.com/feedhenry/fh-ios-sdk-blank-app/blob/master/FHStarterProject/FHStarterProject-Info.plist#L14), not used else where in fh-templates app. Is it still useful templating?

### CODE REVIEW

**Comment by wei-lee** [comment]
Looks good. Don't merge yet until we have deployed the Cocoapods support for production. It has been deployed to staging. Could you do some more testing there. The '%id%' will be replaced with the correct app id when imported into the platform. It is still used.

**Comment by corinnekrych** [comment]
@wei-lee do you know when we're planning to deploy to staging so we can merge this PR?
We need to update to 2.2.11 before merging.

**Comment by wei-lee** [comment]
@corinnekrych I am not really sure. It really depends on when QE can test and sign off.

**Comment by corinnekrych** [comment]
Closing this on for now.

**Pull request closed without merging**
