### PR TITLE
Push.support.fh.2.2.11

### PR DESCRIPTION
**Pull request by corinnekrych**
This PR update the FH.framework for the latest FH.2.2.11

### CODE REVIEW

**Comment by matzew** [comment]
@wei-lee @jasonmadigan can you review?

**Comment by wei-lee** [comment]
LGTM. But better test this on the platform before merging. The only concern I have is about the symlinks in the FH lib.

**Comment by corinnekrych** [comment]
@wei-lee I've tested it on Build Farm on prod with Ciaran
and got a green build.
but would be nice to have @kpiwko to test it.

**Comment by wei-lee** [comment]
@corinnekrych that's fine then. Feel free to merge this.

**Pull request merged**
